#!/bin/bash
# =============================================================================
# OJS Entrypoint Script
# Handles runtime configuration for database connection
# =============================================================================

set -e

echo "========================================="
echo "  OJS - Starting container..."
echo "========================================="

# Ensure required directories exist
mkdir -p /var/www/ojs/files
mkdir -p /var/www/ojs/cache

# ---------------------------------------------------------------------------
# Generate OJS config.inc.php from the template file
# ---------------------------------------------------------------------------
CONFIG_FILE="/var/www/ojs/config.inc.php"
CONFIG_TEMPLATE="/var/www/ojs/config.TEMPLATE.inc.php"

# Use env vars or defaults
DB_HOST="${DATABASE_HOST:-localhost}"
DB_PORT="${DATABASE_PORT:-5432}"
DB_NAME="${DATABASE_NAME:-ojs_db}"
DB_USER="${DATABASE_USER:-ojs_user}"
DB_PASS="${DATABASE_PASSWORD:-ojs_pass}"
DB_DRIVER="${DATABASE_DRIVER:-pgsql}"
OJS_BASE_URL="${OJS_BASE_URL:-http://localhost:8080}"

echo "Configuring OJS..."
echo "  Database: $DB_DRIVER://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME"
echo "  Base URL: $OJS_BASE_URL"

# Start with the template and modify values
if [ -f "$CONFIG_TEMPLATE" ]; then
    cp "$CONFIG_TEMPLATE" "$CONFIG_FILE"
    echo "  Using config.TEMPLATE.inc.php as base"

    # Replace values in config.inc.php using sed
    sed -i "s|base_url = .*|base_url = \"$OJS_BASE_URL\"|" "$CONFIG_FILE"
    sed -i "s|installed = On|installed = Off|" "$CONFIG_FILE"
    sed -i "s|enable_beacon = On|enable_beacon = Off|" "$CONFIG_FILE"

    # Database settings
    sed -i "s|driver = .*|driver = $DB_DRIVER|" "$CONFIG_FILE"
    sed -i "s|host = .*|host = $DB_HOST|" "$CONFIG_FILE"
    sed -i "s|port = .*|port = $DB_PORT|" "$CONFIG_FILE"
    sed -i "s|username = .*|username = $DB_USER|" "$CONFIG_FILE"
    sed -i "s|password = .*|password = $DB_PASS|" "$CONFIG_FILE"
    sed -i "s|name = .*|name = $DB_NAME|" "$CONFIG_FILE"

    # Security - generate random salt and key
    sed -i "s|salt = .*|salt = \"$(openssl rand -hex 32)\"|" "$CONFIG_FILE"
    sed -i "s|encryption_key = .*|encryption_key = \"$(openssl rand -hex 32)\"|" "$CONFIG_FILE"

    # Set email to log mode for testing
    sed -i "s|default = .*|default = log|" "$CONFIG_FILE"

    # Files dir
    sed -i "s|^dir = .*|dir = /var/www/ojs/files|" "$CONFIG_FILE"
else
    echo "  ⚠ Template not found! Building config manually."
    SECURITY_SALT=$(openssl rand -hex 32)
    cat > "$CONFIG_FILE" << CONFIGEOF
; OJS Configuration File
; Generated by Render entrypoint on $(date)

[general]
installed = Off
base_url = "$OJS_BASE_URL"
enable_beacon = Off
time_zone = "UTC"
date_format = %B %d, %Y
date_format_short = %B %d, %Y
datetime_format = %B %d, %Y - %I:%M %p
datetime_format_short = %B %d, %Y - %I:%M %p
time_format = %I:%M %p

[database]
driver = $DB_DRIVER
host = $DB_HOST
port = $DB_PORT
username = $DB_USER
password = $DB_PASS
name = $DB_NAME

[security]
force_ssl = Off
salt = "$SECURITY_SALT"
encryption_key = "$(openssl rand -hex 32)"

[cache]
cache = file
cache_ttl = 3600

[i18n]
locale = en_US
connection_charset = utf8

[files]
dir = /var/www/ojs/files

[oai]
repository_id = ojs

[email]
default = log

[search]
min_word_length = 3
CONFIGEOF
fi

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"
echo "Config written to $CONFIG_FILE"

# Write test PHP file to verify PHP-FPM works
echo "<?php phpinfo(); ?>" > /var/www/ojs/test.php
echo "Created /var/www/ojs/test.php for diagnostics"

# Write diagnostic PHP file for OJS
cat > /var/www/ojs/check.php << 'CHECKPHP'
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

echo "<h1>PHP is working!</h1>";
echo "<p>Nginx + PHP-FPM connection OK</p>";
echo "<p>Document root: " . $_SERVER['DOCUMENT_ROOT'] . "</p>";

echo "<h3>OJS Version:</h3><pre>";
$verFile = '/var/www/ojs/lib/pkp/version.php';
if (file_exists($verFile)) { echo file_get_contents($verFile); }
echo "version.php: " . (file_exists($verFile) ? '✅' : '❌');
echo "</pre>";

echo "<h3>Testing index.php execution:</h3><pre>";
try {
    $_SERVER['REQUEST_METHOD'] = 'GET';
    $_SERVER['REQUEST_URI'] = '/index.php';
    ob_start();
    $result = include '/var/www/ojs/index.php';
    $output = ob_get_clean();
    if ($result === false) {
        echo "⚠ include returned false\n";
    }
    echo "Output length: " . strlen($output) . " bytes\n";
    if (strlen($output) > 0) {
        echo "First 2000 chars of output:\n";
        echo substr($output, 0, 2000);
    }
} catch (Throwable $e) {
    echo "💥 ERROR: " . $e->getMessage() . "\n";
    echo "File: " . $e->getFile() . ":" . $e->getLine() . "\n";
    echo "Trace:\n" . $e->getTraceAsString();
}
echo "</pre>";

echo "<h3>Checking class autoloader:</h3><pre>";
$autoload = '/var/www/ojs/lib/pkp/lib/vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
    echo "Autoloader loaded ✅\n";
    echo "Classes available:\n";
    $classes = get_declared_classes();
    $pkpClasses = array_filter($classes, fn($c) => strpos($c, 'PKP') !== false || strpos($c, 'APP') !== false || strpos($c, 'OJS') !== false);
    foreach ($pkpClasses as $c) echo "  - $c\n";
    if (empty($pkpClasses)) echo "  (no PKP/APP/OJS classes found)\n";
} else {
    echo "Autoloader NOT found ❌\n";
}
echo "</pre>";
?>
CHECKPHP
echo "Created /var/www/ojs/check.php for diagnostics"

# ---------------------------------------------------------------------------
# Fix nginx listen port to match Render's PORT env var
# ---------------------------------------------------------------------------
NGINX_PORT="${PORT:-8080}"
echo "Setting nginx listen port to $NGINX_PORT"
sed -i "s/listen 8080/listen $NGINX_PORT/g" /etc/nginx/nginx.conf
sed -i "s/listen \[::\]:8080/listen \[::\]:$NGINX_PORT/g" /etc/nginx/nginx.conf

# ---------------------------------------------------------------------------
# Fix permissions
# ---------------------------------------------------------------------------
chown -R www-data:www-data /var/www/ojs/files
chown -R www-data:www-data /var/www/ojs/cache
chmod -R 775 /var/www/ojs/files
chmod -R 775 /var/www/ojs/cache

# ---------------------------------------------------------------------------
# Test configurations before starting services
# ---------------------------------------------------------------------------
echo ""
echo "Testing Nginx configuration..."
nginx -t 2>&1 || { echo "Nginx config test failed!"; cat /var/log/nginx/error.log 2>/dev/null; exit 1; }

echo "Testing PHP-FPM configuration..."
php-fpm8.1 --test 2>&1 || { echo "PHP-FPM config test failed!"; exit 1; }

# ---------------------------------------------------------------------------
# Start services via supervisor
# ---------------------------------------------------------------------------
echo ""
echo "Starting Nginx and PHP-FPM..."
echo "========================================="

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
