#!/bin/bash
# =============================================================================
# OJS Entrypoint Script
# Handles runtime configuration for database connection
# =============================================================================

set -e

echo "========================================="
echo "  OJS - Starting container..."
echo "========================================="

# Ensure required directories exist
mkdir -p /var/www/ojs/files
mkdir -p /var/www/ojs/cache

# ---------------------------------------------------------------------------
# Generate OJS config.inc.php from environment variables
# ---------------------------------------------------------------------------
CONFIG_FILE="/var/www/ojs/config.inc.php"

# Use env vars or defaults
DB_HOST="${DATABASE_HOST:-localhost}"
DB_PORT="${DATABASE_PORT:-5432}"
DB_NAME="${DATABASE_NAME:-ojs_db}"
DB_USER="${DATABASE_USER:-ojs_user}"
DB_PASS="${DATABASE_PASSWORD:-ojs_pass}"
DB_DRIVER="${DATABASE_DRIVER:-pgsql}"

OJS_ADMIN_EMAIL="${OJS_ADMIN_EMAIL:-admin@journal.org}"

# Generate a unique salt key for security
SECURITY_SALT=$(openssl rand -hex 32)

# OJS requires a base URL for the installer
OJS_BASE_URL="${OJS_BASE_URL:-http://localhost:8080}"

echo "Configuring OJS..."
echo "  Database: $DB_DRIVER://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME"
echo "  Base URL: $OJS_BASE_URL"

# Generate config.inc.php
cat > "$CONFIG_FILE" << CONFIGEOF
; OJS Configuration File
; Generated by Render entrypoint on $(date)

[general]
installed = Off
base_url = "$OJS_BASE_URL"
enable_beacon = Off
time_zone = "UTC"

[database]
driver = $DB_DRIVER
host = $DB_HOST
port = $DB_PORT
username = $DB_USER
password = $DB_PASS
name = $DB_NAME

[security]
force_ssl = Off
salt = "$SECURITY_SALT"
encryption_key = "$(openssl rand -hex 32)"

[cache]
cache = file
cache_ttl = 3600

[i18n]
locale = en_US
connection_charset = utf8

[files]
dir = /var/www/ojs/files

[oai]
repository_id = ojs

[search]
min_word_length = 3
CONFIGEOF

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"

echo "Config written to $CONFIG_FILE"

# ---------------------------------------------------------------------------
# Fix permissions
# ---------------------------------------------------------------------------
chown -R www-data:www-data /var/www/ojs/files
chown -R www-data:www-data /var/www/ojs/cache
chmod -R 775 /var/www/ojs/files
chmod -R 775 /var/www/ojs/cache

# ---------------------------------------------------------------------------
# Start services via supervisor
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Test configurations before starting services
# ---------------------------------------------------------------------------
echo ""
echo "Testing Nginx configuration..."
nginx -t 2>&1 || { echo "Nginx config test failed!"; cat /var/log/nginx/error.log 2>/dev/null; exit 1; }

echo "Testing PHP-FPM configuration..."
php-fpm8.1 --test 2>&1 || { echo "PHP-FPM config test failed!"; exit 1; }

# ---------------------------------------------------------------------------
# Start services via supervisor
# ---------------------------------------------------------------------------
echo ""
echo "Starting Nginx and PHP-FPM..."
echo "========================================="

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
