#!/bin/bash
# =============================================================================
# OJS Entrypoint Script
# Handles runtime configuration for database connection
# =============================================================================

set -e

echo "========================================="
echo "  OJS - Starting container..."
echo "========================================="

# Ensure required directories exist
mkdir -p /var/www/ojs/files
mkdir -p /var/www/ojs/cache

# ---------------------------------------------------------------------------
# Generate OJS config.inc.php from environment variables
# ---------------------------------------------------------------------------
CONFIG_FILE="/var/www/ojs/config.inc.php"

# Use env vars or defaults
DB_HOST="${DATABASE_HOST:-localhost}"
DB_PORT="${DATABASE_PORT:-5432}"
DB_NAME="${DATABASE_NAME:-ojs_db}"
DB_USER="${DATABASE_USER:-ojs_user}"
DB_PASS="${DATABASE_PASSWORD:-ojs_pass}"
DB_DRIVER="${DATABASE_DRIVER:-pgsql}"

OJS_ADMIN_EMAIL="${OJS_ADMIN_EMAIL:-admin@journal.org}"

# Generate a unique salt key for security
SECURITY_SALT=$(openssl rand -hex 32)

# OJS requires a base URL for the installer
OJS_BASE_URL="${OJS_BASE_URL:-http://localhost:8080}"

echo "Configuring OJS..."
echo "  Database: $DB_DRIVER://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME"
echo "  Base URL: $OJS_BASE_URL"

# Generate config.inc.php
cat > "$CONFIG_FILE" << CONFIGEOF
; OJS Configuration File
; Generated by Render entrypoint on $(date)

[general]
installed = Off
base_url = "$OJS_BASE_URL"
enable_beacon = Off
time_zone = "UTC"

[database]
driver = $DB_DRIVER
host = $DB_HOST
port = $DB_PORT
username = $DB_USER
password = $DB_PASS
name = $DB_NAME

[security]
force_ssl = Off
salt = "$SECURITY_SALT"
encryption_key = "$(openssl rand -hex 32)"

[cache]
cache = file
cache_ttl = 3600

[i18n]
locale = en_US
connection_charset = utf8

[files]
dir = /var/www/ojs/files

[oai]
repository_id = ojs

[search]
min_word_length = 3
CONFIGEOF

chown www-data:www-data "$CONFIG_FILE"
chmod 644 "$CONFIG_FILE"

echo "Config written to $CONFIG_FILE"

# Write test PHP file to verify PHP-FPM works
echo "<?php phpinfo(); ?>" > /var/www/ojs/test.php
echo "Created /var/www/ojs/test.php for diagnostics"

# Write diagnostic PHP file for OJS
cat > /var/www/ojs/check.php << 'CHECKPHP'
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

echo "<h1>PHP is working!</h1>";
echo "<p>Nginx + PHP-FPM connection OK</p>";
echo "<p>Document root: " . $_SERVER['DOCUMENT_ROOT'] . "</p>";

echo "<h3>OJS Version:</h3><pre>";
$verFile = '/var/www/ojs/lib/pkp/version.php';
if (file_exists($verFile)) { echo file_get_contents($verFile); }
echo "version.php: " . (file_exists($verFile) ? '✅' : '❌');
echo "</pre>";

echo "<h3>Testing index.php execution:</h3><pre>";
try {
    $_SERVER['REQUEST_METHOD'] = 'GET';
    $_SERVER['REQUEST_URI'] = '/index.php';
    ob_start();
    $result = include '/var/www/ojs/index.php';
    $output = ob_get_clean();
    if ($result === false) {
        echo "⚠ include returned false\n";
    }
    echo "Output length: " . strlen($output) . " bytes\n";
    if (strlen($output) > 0) {
        echo "First 2000 chars of output:\n";
        echo substr($output, 0, 2000);
    }
} catch (Throwable $e) {
    echo "💥 ERROR: " . $e->getMessage() . "\n";
    echo "File: " . $e->getFile() . ":" . $e->getLine() . "\n";
    echo "Trace:\n" . $e->getTraceAsString();
}
echo "</pre>";

echo "<h3>Checking class autoloader:</h3><pre>";
$autoload = '/var/www/ojs/lib/pkp/lib/vendor/autoload.php';
if (file_exists($autoload)) {
    require_once $autoload;
    echo "Autoloader loaded ✅\n";
    echo "Classes available:\n";
    $classes = get_declared_classes();
    $pkpClasses = array_filter($classes, fn($c) => strpos($c, 'PKP') !== false || strpos($c, 'APP') !== false || strpos($c, 'OJS') !== false);
    foreach ($pkpClasses as $c) echo "  - $c\n";
    if (empty($pkpClasses)) echo "  (no PKP/APP/OJS classes found)\n";
} else {
    echo "Autoloader NOT found ❌\n";
}
echo "</pre>";
?>
CHECKPHP
echo "Created /var/www/ojs/check.php for diagnostics"

# ---------------------------------------------------------------------------
# Fix permissions
# ---------------------------------------------------------------------------
chown -R www-data:www-data /var/www/ojs/files
chown -R www-data:www-data /var/www/ojs/cache
chmod -R 775 /var/www/ojs/files
chmod -R 775 /var/www/ojs/cache

# ---------------------------------------------------------------------------
# Test configurations before starting services
# ---------------------------------------------------------------------------
echo ""
echo "Testing Nginx configuration..."
nginx -t 2>&1 || { echo "Nginx config test failed!"; cat /var/log/nginx/error.log 2>/dev/null; exit 1; }

echo "Testing PHP-FPM configuration..."
php-fpm8.1 --test 2>&1 || { echo "PHP-FPM config test failed!"; exit 1; }

# ---------------------------------------------------------------------------
# Start services via supervisor
# ---------------------------------------------------------------------------
echo ""
echo "Starting Nginx and PHP-FPM..."
echo "========================================="

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
